name: api_repository
description: Dart package that manages HTTP API calls for PSN Time Tracker
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3