name: games_repository
description: Dart package that manage Games data for PSN Time Tracker
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  api_repository:
    path: ../api_repository